# Generated by Django 3.2.3 on 2021-05-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210517_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
