# Generated by Django 3.2.3 on 2021-05-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210525_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Сообщение'),
        ),
    ]
